var searchData=
[
  ['cbasevirtmemalloc',['CBaseVirtMemAlloc',['../classvirtmem_1_1CBaseVirtMemAlloc.html',1,'virtmem']]],
  ['cbasevirtptr',['CBaseVirtPtr',['../classvirtmem_1_1CBaseVirtPtr.html',1,'virtmem']]],
  ['clearpages',['clearPages',['../classvirtmem_1_1CBaseVirtMemAlloc.html#af5034f4f0e48a382477dac7890f5a047',1,'virtmem::CBaseVirtMemAlloc']]],
  ['cmemberwrapper',['CMemberWrapper',['../classvirtmem_1_1CVirtPtr_1_1CMemberWrapper.html',1,'virtmem::CVirtPtr']]],
  ['cmultispiramvirtmemalloc',['CMultiSPIRAMVirtMemAlloc',['../classvirtmem_1_1CMultiSPIRAMVirtMemAlloc.html',1,'virtmem']]],
  ['cnill',['CNILL',['../classvirtmem_1_1CNILL.html',1,'virtmem']]],
  ['config_2eh',['config.h',['../config_8h.html',1,'']]],
  ['csdfatlibvirtmemalloc',['CSdfatlibVirtMemAlloc',['../singletonvirtmem_1_1CSdfatlibVirtMemAlloc.html',1,'virtmem']]],
  ['cserramvirtmemalloc',['CSerRAMVirtMemAlloc',['../classvirtmem_1_1CSerRAMVirtMemAlloc.html',1,'virtmem']]],
  ['cspiramvirtmemalloc',['CSPIRAMVirtMemAlloc',['../classvirtmem_1_1CSPIRAMVirtMemAlloc.html',1,'virtmem']]],
  ['cstaticvirtmemalloc',['CStaticVirtMemAlloc',['../classvirtmem_1_1CStaticVirtMemAlloc.html',1,'virtmem']]],
  ['cstdiovirtmemalloc',['CStdioVirtMemAlloc',['../singletonvirtmem_1_1CStdioVirtMemAlloc.html',1,'virtmem']]],
  ['cvaluewrapper',['CValueWrapper',['../classvirtmem_1_1CVirtPtr_1_1CValueWrapper.html',1,'virtmem::CVirtPtr']]],
  ['cvirtmemalloc',['CVirtMemAlloc',['../classvirtmem_1_1CVirtMemAlloc.html',1,'virtmem']]],
  ['cvirtmemalloc_3c_20tproperties_2c_20cmultispiramvirtmemalloc_3c_20spichips_2c_20chipamount_2c_20tproperties_20_3e_20_3e',['CVirtMemAlloc&lt; TProperties, CMultiSPIRAMVirtMemAlloc&lt; SPIChips, chipAmount, TProperties &gt; &gt;',['../classvirtmem_1_1CVirtMemAlloc.html',1,'virtmem']]],
  ['cvirtmemalloc_3c_20tproperties_2c_20csdfatlibvirtmemalloc_3c_20tproperties_20_3e_20_3e',['CVirtMemAlloc&lt; TProperties, CSdfatlibVirtMemAlloc&lt; TProperties &gt; &gt;',['../classvirtmem_1_1CVirtMemAlloc.html',1,'virtmem']]],
  ['cvirtmemalloc_3c_20tproperties_2c_20cserramvirtmemalloc_3c_20iostream_2c_20tproperties_20_3e_20_3e',['CVirtMemAlloc&lt; TProperties, CSerRAMVirtMemAlloc&lt; IOStream, TProperties &gt; &gt;',['../classvirtmem_1_1CVirtMemAlloc.html',1,'virtmem']]],
  ['cvirtmemalloc_3c_20tproperties_2c_20cspiramvirtmemalloc_3c_20tproperties_20_3e_20_3e',['CVirtMemAlloc&lt; TProperties, CSPIRAMVirtMemAlloc&lt; TProperties &gt; &gt;',['../classvirtmem_1_1CVirtMemAlloc.html',1,'virtmem']]],
  ['cvirtmemalloc_3c_20tproperties_2c_20cstaticvirtmemalloc_3c_20poolsize_2c_20tproperties_20_3e_20_3e',['CVirtMemAlloc&lt; TProperties, CStaticVirtMemAlloc&lt; poolSize, TProperties &gt; &gt;',['../classvirtmem_1_1CVirtMemAlloc.html',1,'virtmem']]],
  ['cvirtmemalloc_3c_20tproperties_2c_20cstdiovirtmemalloc_3c_20tproperties_20_3e_20_3e',['CVirtMemAlloc&lt; TProperties, CStdioVirtMemAlloc&lt; TProperties &gt; &gt;',['../classvirtmem_1_1CVirtMemAlloc.html',1,'virtmem']]],
  ['cvirtptr',['CVirtPtr',['../singletonvirtmem_1_1CVirtPtr.html',1,'virtmem']]],
  ['cvirtptrlock',['CVirtPtrLock',['../classvirtmem_1_1CVirtPtrLock.html',1,'virtmem']]],
  ['cvirtptrlock',['CVirtPtrLock',['../classvirtmem_1_1CVirtPtrLock.html#a1dc9915e6f899019a13eba7abc4280df',1,'virtmem::CVirtPtrLock::CVirtPtrLock(const TV &amp;v, TVirtPageSize s, bool ro=false)'],['../classvirtmem_1_1CVirtPtrLock.html#a532b13a6adcc67baad4d3976670a29e8',1,'virtmem::CVirtPtrLock::CVirtPtrLock(void)']]]
];
